-- ============================================================================
--  接口交换平台 · PostgreSQL 12+ 建表脚本
--  使用方式：
--    1) CREATE DATABASE interchange;
--    2) psql -U postgres -d interchange -f schema-postgresql.sql
--    3) 启动参数：--spring.profiles.active=postgresql
-- ============================================================================

-- 平台侧用户扩展属性（账号主数据在业务系统用户表，平台不建用户表）
CREATE TABLE IF NOT EXISTS sys_user_ext (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ext_id            VARCHAR(64)  NOT NULL,
    role              VARCHAR(32),
    status            INTEGER DEFAULT 1,
    api_token         VARCHAR(128),
    platform_password VARCHAR(128),
    last_login_time   TIMESTAMP,
    create_time       TIMESTAMP,
    update_time       TIMESTAMP,
    CONSTRAINT uk_user_ext_ext_id UNIQUE (ext_id)
);
COMMENT ON TABLE sys_user_ext IS '平台用户扩展属性';
COMMENT ON COLUMN sys_user_ext.ext_id IS '业务系统用户主键（t6.sys_user.ID）';
COMMENT ON COLUMN sys_user_ext.api_token IS '接收接口调用令牌';

-- 接入方凭证：appKey / appSecret 用来换 access_token（令牌本身只在缓存里）
CREATE TABLE IF NOT EXISTS api_token (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    app_key         VARCHAR(64)  NOT NULL,
    app_secret      VARCHAR(128) NOT NULL,
    status          INTEGER DEFAULT 1,
    allow_api_codes VARCHAR(512),
    ttl_seconds     INTEGER DEFAULT 7200,
    remark          VARCHAR(255),
    last_used_time  TIMESTAMP,
    create_time     TIMESTAMP,
    update_time     TIMESTAMP,
    CONSTRAINT uk_api_token_app_key UNIQUE (app_key)
);
COMMENT ON TABLE api_token IS '接入方凭证（换票用）';
COMMENT ON COLUMN api_token.allow_api_codes IS '允许调用的接口编码，逗号分隔；空=不限';

-- 接收接口登记表（接口清单）。
-- 平台的接收端点只有一条 POST /api/receive/{apiCode}；这张表决定哪些 apiCode 是"存在"的。
-- 未登记或已停用的接口会被直接拒绝，不会被兜底回执成成功。
-- 本表不含任何令牌信息（令牌在 api_token 凭证 + 服务端签发缓存里）。
CREATE TABLE IF NOT EXISTS receive_api (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_code      VARCHAR(64)  NOT NULL,
    name          VARCHAR(128) NOT NULL,
    status        INT DEFAULT 1,
    auth_required INT DEFAULT 1,
    remark        VARCHAR(255),
    create_time   TIMESTAMP,
    update_time   TIMESTAMP,
    CONSTRAINT uk_receive_api_code UNIQUE (api_code)
);
COMMENT ON TABLE receive_api IS '接收接口登记';

-- 第三方系统（对接方）
CREATE TABLE IF NOT EXISTS partner (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_code VARCHAR(64)  NOT NULL,
    partner_name VARCHAR(128) NOT NULL,
    base_url     VARCHAR(512),
    auth_type    VARCHAR(32),
    auth_user    VARCHAR(128),
    auth_secret  VARCHAR(1024),
    headers_json VARCHAR(4000),
    timeout_ms   INTEGER DEFAULT 15000,
    status       INTEGER DEFAULT 1,
    remark       VARCHAR(512),
    create_time  TIMESTAMP,
    update_time  TIMESTAMP,
    CONSTRAINT uk_partner_code UNIQUE (partner_code)
);

-- 定时推送任务
CREATE TABLE IF NOT EXISTS interface_task (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_code          VARCHAR(64)  NOT NULL,
    task_name          VARCHAR(128) NOT NULL,
    partner_id         BIGINT,
    source_type        VARCHAR(16)  NOT NULL,
    datasource_key     VARCHAR(64) DEFAULT 'main',
    sql_text           TEXT,
    pull_url           VARCHAR(1024),
    pull_method        VARCHAR(8) DEFAULT 'GET',
    pull_headers       VARCHAR(4000),
    fixed_payload      TEXT,
    target_path        VARCHAR(512),
    http_method        VARCHAR(8) DEFAULT 'POST',
    content_type       VARCHAR(128) DEFAULT 'application/json;charset=UTF-8',
    push_mode          VARCHAR(16) DEFAULT 'BATCH',
    headers_json       VARCHAR(4000),
    handler_bean       VARCHAR(64),
    cron_expression    VARCHAR(64),
    timeout_ms         INTEGER DEFAULT 15000,
    enabled            BOOLEAN NOT NULL DEFAULT TRUE,
    remark             VARCHAR(512),
    last_exec_time     TIMESTAMP,
    last_result        VARCHAR(32),
    last_cost_ms       BIGINT,
    create_time        TIMESTAMP,
    update_time        TIMESTAMP,
    CONSTRAINT uk_task_code UNIQUE (task_code)
);
CREATE INDEX IF NOT EXISTS idx_task_enabled ON interface_task (enabled);
CREATE INDEX IF NOT EXISTS idx_task_partner ON interface_task (partner_id);

-- 任务执行日志
CREATE TABLE IF NOT EXISTS task_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id       BIGINT,
    task_code     VARCHAR(64),
    task_name     VARCHAR(128),
    partner_name  VARCHAR(128),
    trace_id      VARCHAR(64),
    trigger_type  VARCHAR(16),
    start_time    TIMESTAMP,
    end_time      TIMESTAMP,
    cost_ms       BIGINT,
    status        VARCHAR(16),
    total_count   INTEGER DEFAULT 0,
    success_count INTEGER DEFAULT 0,
    fail_count    INTEGER DEFAULT 0,
    target_url    VARCHAR(1024),
    request_body  TEXT,
    response_body TEXT,
    error_msg     TEXT,
    create_time   TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_log_task_code ON task_log (task_code);
CREATE INDEX IF NOT EXISTS idx_log_start_time ON task_log (start_time);
CREATE INDEX IF NOT EXISTS idx_log_status ON task_log (status);

-- 接收日志
CREATE TABLE IF NOT EXISTS receive_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_code      VARCHAR(64),
    trace_id      VARCHAR(64),
    http_method   VARCHAR(8),
    remote_ip     VARCHAR(64),
    caller        VARCHAR(64),
    headers       VARCHAR(4000),
    request_body  TEXT,
    response_body TEXT,
    status        VARCHAR(16),
    error_msg     TEXT,
    cost_ms       BIGINT,
    receive_time  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_recv_api_code ON receive_log (api_code);
CREATE INDEX IF NOT EXISTS idx_recv_time ON receive_log (receive_time);

-- ----------------------------------------------------------------------------
-- 关于管理员账号：
--   不要在本脚本里手工插入 admin（BCrypt 散列与密码强绑定，手抄散列会导致登录失败）。
--   应用首次启动时会自动创建： admin / Admin@123
-- ----------------------------------------------------------------------------
